comment: "This issue is closed because it does not meet our issue template. Please read it."
issueConfigs:
- content:
# bug report
  - "Library filename"
  - "Library label"
  - "Library team"
  - "Library relative URL"
caseInsensitive: false
label: "closed by bot"
